### ISSUE TITLE
Digital Portfolio - Pedro

### ISSUE THREAD

**Issue by PedroBMedeiros** [PedroBMedeiros/P2-Anteaters#19]
- [x] Implement Questions page with a user to admin messaging system
- - [x] Reserch possible pathways: [REST API?](https://docs.google.com/presentation/d/1lNms8t5g0FZC2XXmGUsp_-vKl_LqKp_nIEezYfmejsE/edit#slide=id.gd4f40be10b_0_249), [React](https://www.freecodecamp.org/news/how-to-build-a-react-js-chat-app-in-10-minutes-c9233794642b/)
- - [x] Begin coding
- - [x] Polish final product
- [x] Create new route for connection with user using REST API
- - [x] Display todos of each user
- - [x] Understand new file format
- [x] Connect to crossover group's API

**Comment by OpticStranger** [comment]
I like the data/API-driven ticket; correlates well to our PBL learning goals. I like the simple layout and organization of the ticket, easy to read. How will the database be stored? POSTMAN? SQLLite? All in all good plan.

**Comment by MaxVukovich** [comment]
Good thought on adding the API to this section of your "planner" theme. Database input on this part is a necessary part for PBL learning. How will you be implementing and using data? How are you going to incorporate a Rest API?

**Comment by andrewc26** [comment]
I think this is a good plan of action and a well thought out ticket. I like the idea of incorporating  a rest API into your project planner project theme, but how is it going to improve your project? The questions page is also a great idea. Nice job.
