### ISSUE TITLE
Digital Portfolio - Pedro

### ISSUE THREAD

**Issue by PedroBMedeiros** [PedroBMedeiros/P2-Anteaters#2]
- [x] AP Exam Content Summary using Barron's Review 
- [x] About & Contact Us page in html with initial messaging system for user questions
- [ ] Implement a daily notecard for the planner

**Comment by jm1021** [comment]
Good start on issue and structure.  No links to tangibles 2/3

**Comment by jm1021** [comment]
I think you sent me something before and I provided a 4/3.  But I have no idea why, but I will let that score remain.
