### ISSUE TITLE
Digital Portfolio -  Mackenzie

### ISSUE THREAD

**Issue by kenzie-rylie** [PedroBMedeiros/P2-Anteaters#3]
- [x] create signup system - 
- [x] front end aspects - designing a simple and clean format for the overall website. I am going for dark theme.
- [x] incorporate react into the project - using react for the frontend aspects and functions of the planner

5/18-21/2021

- Tangibles: 
[Runtime Link](https://p2-anteaters-todos.netlify.app/)
[ video of running code](https://www.loom.com/share/64c37157811647b8af4055f427d97fe1)
- Code links: 
  - [ dashboard.jsx](https://github.com/PedroBMedeiros/P2-Anteaters/blob/main/client/src/Pages/Dashboard.jsx) –– responsible for all the functionality in the dashboard page(showing todos, adding todos)
  - [form.jsx](https://github.com/PedroBMedeiros/P2-Anteaters/blob/main/client/src/components/Form/Form.jsx) –– responsible for the login and signup (authentication)
- [Commits](https://github.com/PedroBMedeiros/P2-Anteaters/commits?author=kenzie-rylie)

**Comment by kenzie-rylie** [comment]
- [ ] create signup system
- [ ] front end aspects
- [ ] incorporate react into the project

5/18/2021

- Tangibles:
- Code links:
- [Commits](https://github.com/PedroBMedeiros/P2-Anteaters/commits?author=kenzie-rylie)

**Comment by jm1021** [comment]
Very impressive ticket.  You could teach us all about jsx.  The video is spectacular. 4/3

**Comment by jm1021** [comment]
Also, thanks for being a leader and getting the issue board setup for everyone.  I am impressed.

**Comment by AdamHolbel** [comment]
Looks really well made and seems to work properly. Maybe work on the styling of the login page more

**Comment by maggie3000** [comment]
Nice login page, also cool to see you already finished the backend for it too.

**Comment by mustafasharaf04** [comment]
I think that it's awesome that you have a simple and clean goal as well as a simple and clean login page. Hopefully the login page can work properly in the next coming week. Good work!

**Comment by PedroBMedeiros** [comment]
Sign up system seems to be working well and design while could use some touching up is looking very solid for a first draw up. React seems to have worked seemlessly
