### ISSUE TITLE
Digital Portfolio - Anthony

### ISSUE THREAD

**Issue by kenzie-rylie** [PedroBMedeiros/P2-Anteaters#4]
- [x] convert existing project into rest api
- [x] create 1:1 relational database for user task

**Comment by jm1021** [comment]
Thanks for starting and issue.  I don't see any links to tangibles.  2/3

**Comment by PedroBMedeiros** [comment]
The project is now in REST API and is functioning as intended. Next up,  connecting to the crossover team.
