### ISSUE TITLE
Digital Portfolio - Naweid

### ISSUE THREAD

**Issue by kenzie-rylie** [PedroBMedeiros/P2-Anteaters#5]
May 17-21
- [x] css(make contact page look good)

Umbrella Ticket
- [x] work on css and making website look good
- [x] fix login system-fix any errors with it
- [x] create ticket for next week

**Comment by jm1021** [comment]
Naweid, you need to have a more SMART sounding objective.  This could be backed with link of evidence and a commit.  1/3

**Comment by anthonywilsonn** [comment]
Nice Work!

**Comment by nathanlee27** [comment]
I think your ticket can go more in depth and have a bit more but other than that learning how to do css is very important. If the website doesn't look good no one would want to go on it.

**Comment by NoahPidding** [comment]
Maybe a little more effort and specification can go into this ticket, as it does lack a bit of clarity.

**Comment by PedroBMedeiros** [comment]
Your ticket could go a bit more in depth, and I feel like you ticket is not up to date.
