### ISSUE TITLE
Digital Portfolio - Cherry

### ISSUE THREAD

**Issue by PedroBMedeiros** [PedroBMedeiros/P2-Anteaters#6]

**Comment by YanqiaoD** [comment]
- [ ] finish digital portfolio and submit

**Comment by YanqiaoD** [comment]
- [ ] review ap mc test and key knowledge
- [ ] finish digital portfolio and submit

**Comment by jm1021** [comment]
Cherry, good start on goals.  You need to show tangible evidence.  Look and Mackenzie for example.  You had same content as she did on Digital Portfolio.  2/3

**Comment by maggie3000** [comment]
looks good!

**Comment by AdamHolbel** [comment]
Remember to study hard over the next few days as our AP exam is coming up. Lots of helpful links in the Coding channel on Slack. I would recommend this [Study Guide](https://docs.google.com/document/d/1JO4-AmY5pNLwSPj45ztj9Q0lW-4nGi17Hg8hTVDGRc8/edit) made by my teammate Kaila

**Comment by KetherBuG** [comment]
Hey Cherry, nice tickets. You might wanna add in more actionable items for completing the pbl stuff like the front end htmls or backend routing.

**Comment by PedroBMedeiros** [comment]
The ticket does not seem to be up to date with us being done with the AP Exam
